server:
  port: 9003
spring:
  application:
    name: railway-order-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host:
      port:
  cloud:
    nacos:
      discovery:
        server-addr:
      password: nacos
      username: nacos
#    sentinel:
#      transport:
#        dashboard: localhost:8686
#        port: 8719
rocketmq:
  name-server:
  producer:
    group: railway_order-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

framework:
  cache:
    redis:
      value-time-unit: days
      value-timeout: 16
  base:
    fastjson:
      safe-mode: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    tags:
#      application: ${spring.application.name}
